# © 2025 HarmonyCares
# All rights reserved.

"""
Pydantic dataclass model for sbmhh schema.

Generated from: _schemas/sbmhh.yml
"""

from datetime import date

from pydantic import Field
from pydantic.dataclasses import dataclass

from acoharmony._registry import (
    register_schema,
    with_four_icli,
    with_parser,
    with_storage,
    with_transform,
)


@register_schema(
    name="sbmhh",
    version=2,
    tier="bronze",
    description="Shadow Bundles Monthly Home Health",
    file_patterns={"reach": ["D????.PY????.??.SBMHH.D??????.T*.csv"]},
)
@with_parser(
    type="csv", delimiter=",", encoding="utf-8", has_header=True, embedded_transforms=False
)
@with_transform()
@with_storage(
    tier="bronze",
    file_patterns={"reach": ["D????.PY????.??.SBMHH.D??????.T*.csv"]},
    silver={"output_name": "sbmhh.parquet", "refresh_frequency": "monthly"},
)
@with_four_icli(
    category="Reports",
    file_type_code=243,
    file_pattern="D????.PY????.??.SBMHH.D??????.T*.csv",
    extract_zip=False,
    refresh_frequency="monthly",
)
@dataclass
class Sbmhh:
    """
    Shadow Bundles Monthly Home Health
    """

    episode_id: str | None = Field(default=None, description="Episode identifier")
    curhic_uneq: str | None = Field(default=None, description="Current HIC unique identifier")
    mbi_id: str | None = Field(default=None, description="Medicare Beneficiary Identifier")
    claimno: str | None = Field(default=None, description="Claim number")
    sgmt_num: int | None = Field(default=None, description="Segment number")
    from_dt: date | None = Field(default=None, description="Service from date")
    thru_dt: date | None = Field(default=None, description="Service through date")
    provider: str | None = Field(default=None, description="Provider number")
    hcpscd01: str | None = Field(default=None, description="HCPCS code 1")
    hcpscd02: str | None = Field(default=None, description="HCPCS code 2")
    hcpscd03: str | None = Field(default=None, description="HCPCS code 3")
    hcpscd04: str | None = Field(default=None, description="HCPCS code 4")
    hcpscd05: str | None = Field(default=None, description="HCPCS code 5")
    hcpscd06: str | None = Field(default=None, description="HCPCS code 6")
    hcpscd07: str | None = Field(default=None, description="HCPCS code 7")
    hcpscd08: str | None = Field(default=None, description="HCPCS code 8")
    hcpscd09: str | None = Field(default=None, description="HCPCS code 9")
    hcpscd10: str | None = Field(default=None, description="HCPCS code 10")
    hcpscd11: str | None = Field(default=None, description="HCPCS code 11")
    hcpscd12: str | None = Field(default=None, description="HCPCS code 12")
    hcpscd13: str | None = Field(default=None, description="HCPCS code 13")
    hcpscd14: str | None = Field(default=None, description="HCPCS code 14")
    hcpscd15: str | None = Field(default=None, description="HCPCS code 15")
    hcpscd16: str | None = Field(default=None, description="HCPCS code 16")
    hcpscd17: str | None = Field(default=None, description="HCPCS code 17")
    hcpscd18: str | None = Field(default=None, description="HCPCS code 18")
    hcpscd19: str | None = Field(default=None, description="HCPCS code 19")
    hcpscd20: str | None = Field(default=None, description="HCPCS code 20")
    hcpscd21: str | None = Field(default=None, description="HCPCS code 21")
    hcpscd22: str | None = Field(default=None, description="HCPCS code 22")
    hcpscd23: str | None = Field(default=None, description="HCPCS code 23")
    hcpscd24: str | None = Field(default=None, description="HCPCS code 24")
    hcpscd25: str | None = Field(default=None, description="HCPCS code 25")
    hcpscd26: str | None = Field(default=None, description="HCPCS code 26")
    hcpscd27: str | None = Field(default=None, description="HCPCS code 27")
    hcpscd28: str | None = Field(default=None, description="HCPCS code 28")
    hcpscd29: str | None = Field(default=None, description="HCPCS code 29")
    hcpscd30: str | None = Field(default=None, description="HCPCS code 30")
    hcpscd31: str | None = Field(default=None, description="HCPCS code 31")
    hcpscd32: str | None = Field(default=None, description="HCPCS code 32")
    hcpscd33: str | None = Field(default=None, description="HCPCS code 33")
    hcpscd34: str | None = Field(default=None, description="HCPCS code 34")
    hcpscd35: str | None = Field(default=None, description="HCPCS code 35")
    hcpscd36: str | None = Field(default=None, description="HCPCS code 36")
    hcpscd37: str | None = Field(default=None, description="HCPCS code 37")
    hcpscd38: str | None = Field(default=None, description="HCPCS code 38")
    hcpscd39: str | None = Field(default=None, description="HCPCS code 39")
    hcpscd40: str | None = Field(default=None, description="HCPCS code 40")
    hcpscd41: str | None = Field(default=None, description="HCPCS code 41")
    hcpscd42: str | None = Field(default=None, description="HCPCS code 42")
    hcpscd43: str | None = Field(default=None, description="HCPCS code 43")
    hcpscd44: str | None = Field(default=None, description="HCPCS code 44")
    hcpscd45: str | None = Field(default=None, description="HCPCS code 45")
    pmt_amt: str | None = Field(default=None, description="Payment amount")
    prpayamt: str | None = Field(default=None, description="Primary payer amount")
    rvncvr01: str | None = Field(default=None, description="Revenue center code 1")
    rvncvr02: str | None = Field(default=None, description="Revenue center code 2")
    rvncvr03: str | None = Field(default=None, description="Revenue center code 3")
    rvncvr04: str | None = Field(default=None, description="Revenue center code 4")
    rvncvr05: str | None = Field(default=None, description="Revenue center code 5")
    rvncvr06: str | None = Field(default=None, description="Revenue center code 6")
    rvncvr07: str | None = Field(default=None, description="Revenue center code 7")
    rvncvr08: str | None = Field(default=None, description="Revenue center code 8")
    rvncvr09: str | None = Field(default=None, description="Revenue center code 9")
    rvncvr10: str | None = Field(default=None, description="Revenue center code 10")
    rvncvr11: str | None = Field(default=None, description="Revenue center code 11")
    rvncvr12: str | None = Field(default=None, description="Revenue center code 12")
    rvncvr13: str | None = Field(default=None, description="Revenue center code 13")
    rvncvr14: str | None = Field(default=None, description="Revenue center code 14")
    rvncvr15: str | None = Field(default=None, description="Revenue center code 15")
    rvncvr16: str | None = Field(default=None, description="Revenue center code 16")
    rvncvr17: str | None = Field(default=None, description="Revenue center code 17")
    rvncvr18: str | None = Field(default=None, description="Revenue center code 18")
    rvncvr19: str | None = Field(default=None, description="Revenue center code 19")
    rvncvr20: str | None = Field(default=None, description="Revenue center code 20")
    rvncvr21: str | None = Field(default=None, description="Revenue center code 21")
    rvncvr22: str | None = Field(default=None, description="Revenue center code 22")
    rvncvr23: str | None = Field(default=None, description="Revenue center code 23")
    rvncvr24: str | None = Field(default=None, description="Revenue center code 24")
    rvncvr25: str | None = Field(default=None, description="Revenue center code 25")
    rvncvr26: str | None = Field(default=None, description="Revenue center code 26")
    rvncvr27: str | None = Field(default=None, description="Revenue center code 27")
    rvncvr28: str | None = Field(default=None, description="Revenue center code 28")
    rvncvr29: str | None = Field(default=None, description="Revenue center code 29")
    rvncvr30: str | None = Field(default=None, description="Revenue center code 30")
    rvncvr31: str | None = Field(default=None, description="Revenue center code 31")
    rvncvr32: str | None = Field(default=None, description="Revenue center code 32")
    rvncvr33: str | None = Field(default=None, description="Revenue center code 33")
    rvncvr34: str | None = Field(default=None, description="Revenue center code 34")
    rvncvr35: str | None = Field(default=None, description="Revenue center code 35")
    rvncvr36: str | None = Field(default=None, description="Revenue center code 36")
    rvncvr37: str | None = Field(default=None, description="Revenue center code 37")
    rvncvr38: str | None = Field(default=None, description="Revenue center code 38")
    rvncvr39: str | None = Field(default=None, description="Revenue center code 39")
    rvncvr40: str | None = Field(default=None, description="Revenue center code 40")
    rvncvr41: str | None = Field(default=None, description="Revenue center code 41")
    rvncvr42: str | None = Field(default=None, description="Revenue center code 42")
    rvncvr43: str | None = Field(default=None, description="Revenue center code 43")
    rvncvr44: str | None = Field(default=None, description="Revenue center code 44")
    rvncvr45: str | None = Field(default=None, description="Revenue center code 45")
    rvchrg01: str | None = Field(default=None, description="Revenue charge amount 1")
    rvchrg02: str | None = Field(default=None, description="Revenue charge amount 2")
    rvchrg03: str | None = Field(default=None, description="Revenue charge amount 3")
    rvchrg04: str | None = Field(default=None, description="Revenue charge amount 4")
    rvchrg05: str | None = Field(default=None, description="Revenue charge amount 5")
    rvchrg06: str | None = Field(default=None, description="Revenue charge amount 6")
    rvchrg07: str | None = Field(default=None, description="Revenue charge amount 7")
    rvchrg08: str | None = Field(default=None, description="Revenue charge amount 8")
    rvchrg09: str | None = Field(default=None, description="Revenue charge amount 9")
    rvchrg10: str | None = Field(default=None, description="Revenue charge amount 10")
    rvchrg11: str | None = Field(default=None, description="Revenue charge amount 11")
    rvchrg12: str | None = Field(default=None, description="Revenue charge amount 12")
    rvchrg13: str | None = Field(default=None, description="Revenue charge amount 13")
    rvchrg14: str | None = Field(default=None, description="Revenue charge amount 14")
    rvchrg15: str | None = Field(default=None, description="Revenue charge amount 15")
    rvchrg16: str | None = Field(default=None, description="Revenue charge amount 16")
    rvchrg17: str | None = Field(default=None, description="Revenue charge amount 17")
    rvchrg18: str | None = Field(default=None, description="Revenue charge amount 18")
    rvchrg19: str | None = Field(default=None, description="Revenue charge amount 19")
    rvchrg20: str | None = Field(default=None, description="Revenue charge amount 20")
    rvchrg21: str | None = Field(default=None, description="Revenue charge amount 21")
    rvchrg22: str | None = Field(default=None, description="Revenue charge amount 22")
    rvchrg23: str | None = Field(default=None, description="Revenue charge amount 23")
    rvchrg24: str | None = Field(default=None, description="Revenue charge amount 24")
    rvchrg25: str | None = Field(default=None, description="Revenue charge amount 25")
    rvchrg26: str | None = Field(default=None, description="Revenue charge amount 26")
    rvchrg27: str | None = Field(default=None, description="Revenue charge amount 27")
    rvchrg28: str | None = Field(default=None, description="Revenue charge amount 28")
    rvchrg29: str | None = Field(default=None, description="Revenue charge amount 29")
    rvchrg30: str | None = Field(default=None, description="Revenue charge amount 30")
    rvchrg31: str | None = Field(default=None, description="Revenue charge amount 31")
    rvchrg32: str | None = Field(default=None, description="Revenue charge amount 32")
    rvchrg33: str | None = Field(default=None, description="Revenue charge amount 33")
    rvchrg34: str | None = Field(default=None, description="Revenue charge amount 34")
    rvchrg35: str | None = Field(default=None, description="Revenue charge amount 35")
    rvchrg36: str | None = Field(default=None, description="Revenue charge amount 36")
    rvchrg37: str | None = Field(default=None, description="Revenue charge amount 37")
    rvchrg38: str | None = Field(default=None, description="Revenue charge amount 38")
    rvchrg39: str | None = Field(default=None, description="Revenue charge amount 39")
    rvchrg40: str | None = Field(default=None, description="Revenue charge amount 40")
    rvchrg41: str | None = Field(default=None, description="Revenue charge amount 41")
    rvchrg42: str | None = Field(default=None, description="Revenue charge amount 42")
    rvchrg43: str | None = Field(default=None, description="Revenue charge amount 43")
    rvchrg44: str | None = Field(default=None, description="Revenue charge amount 44")
    rvchrg45: str | None = Field(default=None, description="Revenue charge amount 45")
    rvcntr01: str | None = Field(default=None, description="Revenue center count 1")
    rvcntr02: str | None = Field(default=None, description="Revenue center count 2")
    rvcntr03: str | None = Field(default=None, description="Revenue center count 3")
    rvcntr04: str | None = Field(default=None, description="Revenue center count 4")
    rvcntr05: str | None = Field(default=None, description="Revenue center count 5")
    rvcntr06: str | None = Field(default=None, description="Revenue center count 6")
    rvcntr07: str | None = Field(default=None, description="Revenue center count 7")
    rvcntr08: str | None = Field(default=None, description="Revenue center count 8")
    rvcntr09: str | None = Field(default=None, description="Revenue center count 9")
    rvcntr10: str | None = Field(default=None, description="Revenue center count 10")
    rvcntr11: str | None = Field(default=None, description="Revenue center count 11")
    rvcntr12: str | None = Field(default=None, description="Revenue center count 12")
    rvcntr13: str | None = Field(default=None, description="Revenue center count 13")
    rvcntr14: str | None = Field(default=None, description="Revenue center count 14")
    rvcntr15: str | None = Field(default=None, description="Revenue center count 15")
    rvcntr16: str | None = Field(default=None, description="Revenue center count 16")
    rvcntr17: str | None = Field(default=None, description="Revenue center count 17")
    rvcntr18: str | None = Field(default=None, description="Revenue center count 18")
    rvcntr19: str | None = Field(default=None, description="Revenue center count 19")
    rvcntr20: str | None = Field(default=None, description="Revenue center count 20")
    rvcntr21: str | None = Field(default=None, description="Revenue center count 21")
    rvcntr22: str | None = Field(default=None, description="Revenue center count 22")
    rvcntr23: str | None = Field(default=None, description="Revenue center count 23")
    rvcntr24: str | None = Field(default=None, description="Revenue center count 24")
    rvcntr25: str | None = Field(default=None, description="Revenue center count 25")
    rvcntr26: str | None = Field(default=None, description="Revenue center count 26")
    rvcntr27: str | None = Field(default=None, description="Revenue center count 27")
    rvcntr28: str | None = Field(default=None, description="Revenue center count 28")
    rvcntr29: str | None = Field(default=None, description="Revenue center count 29")
    rvcntr30: str | None = Field(default=None, description="Revenue center count 30")
    rvcntr31: str | None = Field(default=None, description="Revenue center count 31")
    rvcntr32: str | None = Field(default=None, description="Revenue center count 32")
    rvcntr33: str | None = Field(default=None, description="Revenue center count 33")
    rvcntr34: str | None = Field(default=None, description="Revenue center count 34")
    rvcntr35: str | None = Field(default=None, description="Revenue center count 35")
    rvcntr36: str | None = Field(default=None, description="Revenue center count 36")
    rvcntr37: str | None = Field(default=None, description="Revenue center count 37")
    rvcntr38: str | None = Field(default=None, description="Revenue center count 38")
    rvcntr39: str | None = Field(default=None, description="Revenue center count 39")
    rvcntr40: str | None = Field(default=None, description="Revenue center count 40")
    rvcntr41: str | None = Field(default=None, description="Revenue center count 41")
    rvcntr42: str | None = Field(default=None, description="Revenue center count 42")
    rvcntr43: str | None = Field(default=None, description="Revenue center count 43")
    rvcntr44: str | None = Field(default=None, description="Revenue center count 44")
    rvcntr45: str | None = Field(default=None, description="Revenue center count 45")
    rev_dt01: date | None = Field(default=None, description="Revenue date 1")
    rev_dt02: date | None = Field(default=None, description="Revenue date 2")
    rev_dt03: date | None = Field(default=None, description="Revenue date 3")
    rev_dt04: date | None = Field(default=None, description="Revenue date 4")
    rev_dt05: date | None = Field(default=None, description="Revenue date 5")
    rev_dt06: date | None = Field(default=None, description="Revenue date 6")
    rev_dt07: date | None = Field(default=None, description="Revenue date 7")
    rev_dt08: date | None = Field(default=None, description="Revenue date 8")
    rev_dt09: date | None = Field(default=None, description="Revenue date 9")
    rev_dt10: date | None = Field(default=None, description="Revenue date 10")
    rev_dt11: date | None = Field(default=None, description="Revenue date 11")
    rev_dt12: date | None = Field(default=None, description="Revenue date 12")
    rev_dt13: date | None = Field(default=None, description="Revenue date 13")
    rev_dt14: date | None = Field(default=None, description="Revenue date 14")
    rev_dt15: date | None = Field(default=None, description="Revenue date 15")
    rev_dt16: date | None = Field(default=None, description="Revenue date 16")
    rev_dt17: date | None = Field(default=None, description="Revenue date 17")
    rev_dt18: date | None = Field(default=None, description="Revenue date 18")
    rev_dt19: date | None = Field(default=None, description="Revenue date 19")
    rev_dt20: date | None = Field(default=None, description="Revenue date 20")
    rev_dt21: date | None = Field(default=None, description="Revenue date 21")
    rev_dt22: date | None = Field(default=None, description="Revenue date 22")
    rev_dt23: date | None = Field(default=None, description="Revenue date 23")
    rev_dt24: date | None = Field(default=None, description="Revenue date 24")
    rev_dt25: date | None = Field(default=None, description="Revenue date 25")
    rev_dt26: date | None = Field(default=None, description="Revenue date 26")
    rev_dt27: date | None = Field(default=None, description="Revenue date 27")
    rev_dt28: date | None = Field(default=None, description="Revenue date 28")
    rev_dt29: date | None = Field(default=None, description="Revenue date 29")
    rev_dt30: date | None = Field(default=None, description="Revenue date 30")
    rev_dt31: date | None = Field(default=None, description="Revenue date 31")
    rev_dt32: date | None = Field(default=None, description="Revenue date 32")
    rev_dt33: date | None = Field(default=None, description="Revenue date 33")
    rev_dt34: date | None = Field(default=None, description="Revenue date 34")
    rev_dt35: date | None = Field(default=None, description="Revenue date 35")
    rev_dt36: date | None = Field(default=None, description="Revenue date 36")
    rev_dt37: date | None = Field(default=None, description="Revenue date 37")
    rev_dt38: date | None = Field(default=None, description="Revenue date 38")
    rev_dt39: date | None = Field(default=None, description="Revenue date 39")
    rev_dt40: date | None = Field(default=None, description="Revenue date 40")
    rev_dt41: date | None = Field(default=None, description="Revenue date 41")
    rev_dt42: date | None = Field(default=None, description="Revenue date 42")
    rev_dt43: date | None = Field(default=None, description="Revenue date 43")
    rev_dt44: date | None = Field(default=None, description="Revenue date 44")
    rev_dt45: date | None = Field(default=None, description="Revenue date 45")
    rvunt01: int | None = Field(default=None, description="Revenue unit 1")
    rvunt02: int | None = Field(default=None, description="Revenue unit 2")
    rvunt03: int | None = Field(default=None, description="Revenue unit 3")
    rvunt04: int | None = Field(default=None, description="Revenue unit 4")
    rvunt05: int | None = Field(default=None, description="Revenue unit 5")
    rvunt06: int | None = Field(default=None, description="Revenue unit 6")
    rvunt07: int | None = Field(default=None, description="Revenue unit 7")
    rvunt08: int | None = Field(default=None, description="Revenue unit 8")
    rvunt09: int | None = Field(default=None, description="Revenue unit 9")
    rvunt10: int | None = Field(default=None, description="Revenue unit 10")
    rvunt11: int | None = Field(default=None, description="Revenue unit 11")
    rvunt12: int | None = Field(default=None, description="Revenue unit 12")
    rvunt13: int | None = Field(default=None, description="Revenue unit 13")
    rvunt14: int | None = Field(default=None, description="Revenue unit 14")
    rvunt15: int | None = Field(default=None, description="Revenue unit 15")
    rvunt16: int | None = Field(default=None, description="Revenue unit 16")
    rvunt17: int | None = Field(default=None, description="Revenue unit 17")
    rvunt18: int | None = Field(default=None, description="Revenue unit 18")
    rvunt19: int | None = Field(default=None, description="Revenue unit 19")
    rvunt20: int | None = Field(default=None, description="Revenue unit 20")
    rvunt21: int | None = Field(default=None, description="Revenue unit 21")
    rvunt22: int | None = Field(default=None, description="Revenue unit 22")
    rvunt23: int | None = Field(default=None, description="Revenue unit 23")
    rvunt24: int | None = Field(default=None, description="Revenue unit 24")
    rvunt25: int | None = Field(default=None, description="Revenue unit 25")
    rvunt26: int | None = Field(default=None, description="Revenue unit 26")
    rvunt27: int | None = Field(default=None, description="Revenue unit 27")
    rvunt28: int | None = Field(default=None, description="Revenue unit 28")
    rvunt29: int | None = Field(default=None, description="Revenue unit 29")
    rvunt30: int | None = Field(default=None, description="Revenue unit 30")
    rvunt31: int | None = Field(default=None, description="Revenue unit 31")
    rvunt32: int | None = Field(default=None, description="Revenue unit 32")
    rvunt33: int | None = Field(default=None, description="Revenue unit 33")
    rvunt34: int | None = Field(default=None, description="Revenue unit 34")
    rvunt35: int | None = Field(default=None, description="Revenue unit 35")
    rvunt36: int | None = Field(default=None, description="Revenue unit 36")
    rvunt37: int | None = Field(default=None, description="Revenue unit 37")
    rvunt38: int | None = Field(default=None, description="Revenue unit 38")
    rvunt39: int | None = Field(default=None, description="Revenue unit 39")
    rvunt40: int | None = Field(default=None, description="Revenue unit 40")
    rvunt41: int | None = Field(default=None, description="Revenue unit 41")
    rvunt42: int | None = Field(default=None, description="Revenue unit 42")
    rvunt43: int | None = Field(default=None, description="Revenue unit 43")
    rvunt44: int | None = Field(default=None, description="Revenue unit 44")
    rvunt45: int | None = Field(default=None, description="Revenue unit 45")
    lupaind: str | None = Field(default=None, description="LUPA indicator")
    prcrrtrn: str | None = Field(default=None, description="Procedure return")
    clm_allowed: str | None = Field(default=None, description="Claim allowed amount")
    std_allowed: str | None = Field(default=None, description="Standardized allowed amount")
    std_cost_epi_total: str | None = Field(
        default=None, description="Standardized cost episode total"
    )
    dgnscd01: str | None = Field(default=None, description="Diagnosis code 1")
    dgnscd02: str | None = Field(default=None, description="Diagnosis code 2")
    dgnscd03: str | None = Field(default=None, description="Diagnosis code 3")
    dgnscd04: str | None = Field(default=None, description="Diagnosis code 4")
    dgnscd05: str | None = Field(default=None, description="Diagnosis code 5")
    dgnscd06: str | None = Field(default=None, description="Diagnosis code 6")
    dgnscd07: str | None = Field(default=None, description="Diagnosis code 7")
    dgnscd08: str | None = Field(default=None, description="Diagnosis code 8")
    dgnscd09: str | None = Field(default=None, description="Diagnosis code 9")
    dgnscd10: str | None = Field(default=None, description="Diagnosis code 10")
    dgnscd11: str | None = Field(default=None, description="Diagnosis code 11")
    dgnscd12: str | None = Field(default=None, description="Diagnosis code 12")
    dgnscd13: str | None = Field(default=None, description="Diagnosis code 13")
    dgnscd14: str | None = Field(default=None, description="Diagnosis code 14")
    dgnscd15: str | None = Field(default=None, description="Diagnosis code 15")
    dgnscd16: str | None = Field(default=None, description="Diagnosis code 16")
    dgnscd17: str | None = Field(default=None, description="Diagnosis code 17")
    dgnscd18: str | None = Field(default=None, description="Diagnosis code 18")
    dgnscd19: str | None = Field(default=None, description="Diagnosis code 19")
    dgnscd20: str | None = Field(default=None, description="Diagnosis code 20")
    dgnscd21: str | None = Field(default=None, description="Diagnosis code 21")
    dgnscd22: str | None = Field(default=None, description="Diagnosis code 22")
    dgnscd23: str | None = Field(default=None, description="Diagnosis code 23")
    dgnscd24: str | None = Field(default=None, description="Diagnosis code 24")
    dgnscd25: str | None = Field(default=None, description="Diagnosis code 25")
